services:
  - type: web
    name: strapi-backend
    env: node
    plan: free
    repo: https://github.com/giovannifdipasquale/escursioni-cms
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_NAME
        value: escursioni_cms_db
      - key: DATABASE_HOST
        value: postgresql://escursioni_cms_db_user:2oBOA53avOP6rpSeku0OcyuWwokKeKaX@dpg-d1jdos15pdvs73dp1ai0-a/escursioni_cms_db
      - key: DATABASE_PORT
        value: 5432
      - key: DATABASE_USERNAME
        value: escursioni_cms_db_user
      - key: DATABASE_PASSWORD
        value: 2oBOA53avOP6rpSeku0OcyuWwokKeKaX
      - key: JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: DATABASE_SSL
        value: "true"
      - key: DATABASE_SSL_REJECT_UNAUTHORIZED
        value: "false"
